export const strings = {
  app: {
    name: 'Bloom',
  },
  tabs: {
    checkin: 'Check-in',
    calendar: 'Calendario',
    registers: 'Registros',
    records: 'Buscar',
    skills: 'Habilidades',
    profile: 'Tu',
  },
  auth: {
    login: 'Iniciar sesión',
    register: 'Crear cuenta',
    forgotPassword: 'Recuperar contraseña',
    email: 'Correo electrónico',
    password: 'Contraseña',
    confirmPassword: 'Confirmar contraseña',
    displayName: 'Nombre',
    loginButton: 'Entrar',
    registerButton: 'Registrarse',
    forgotPasswordButton: 'Enviar enlace',
    noAccount: '¿No tienes cuenta?',
    hasAccount: '¿Ya tienes cuenta?',
    forgotPasswordLink: '¿Olvidaste tu contraseña?',
    backToLogin: 'Volver al inicio',
    logout: 'Cerrar sesión',
  },
  checkin: {
    title: '¿Cómo te has sentido hoy?',
    newCheckin: 'Registro diario',
    todayRecords: 'Registros de hoy',
    noRecordsToday: 'Aún no has registrado nada hoy',
    emotion: '¿Cuál es tu emoción predominante?',
    intensity: 'Intensidad',
    sleep: '¿Cómo has dormido?',
    hunger: 'Nivel de hambre',
    cycle: 'Fase del ciclo',
    events: 'Eventos importantes',
    eventTitle: 'Título del evento',
    eventDescription: 'Descripción',
    addEvent: 'Añadir otro evento',
    notes: 'Notas adicionales',
    notesPlaceholder: 'Escribe lo que quieras...',
    save: 'Guardar registro',
    saved: 'Registro guardado',
    sectionDaily: 'Registros diarios',
    sectionEmotional: 'Registros emocionales',
  },
  calendar: {
    title: 'Calendario',
    noRecords: 'No hay registros para este día',
    addRecord: 'Añadir registro',
  },
  tu: {
    insights: 'Insights',
    insightsDesc: 'Tu resumen emocional',
    compartido: 'Compartido',
    compartidoDesc: 'Jardín compartido contigo',
    habilidades: 'Habilidades',
    habilidadesDesc: 'Recursos y técnicas',
    compartirDatos: 'Compartir datos',
    compartirDatosDesc: 'Gestiona quién ve tu jardín',
    premium: 'Premium',
    premiumDesc: 'Desbloquea funciones avanzadas',
    settings: 'Ajustes',
    about: 'Acerca de',
    version: 'Versión',
  },
  search: {
    title: 'Buscar',
    subtitle: 'Busca en tus registros',
    segmentAll: 'Todos',
    segmentCheckin: 'Check-in',
    segmentRegister: 'Observar y describir',
    placeholder: 'Buscar por texto...',
    emotionsLabel: 'Filtrar por emociones',
    dateFrom: 'Desde',
    dateTo: 'Hasta',
    searchButton: 'Buscar',
    clearFilters: 'Limpiar filtros',
    results: 'resultados',
    oneResult: 'resultado',
    noResults: 'No se encontraron registros',
    noResultsHint: 'Prueba con otros filtros o términos de búsqueda',
    noRecords: 'Aún no tienes registros',
  },
  registers: {
    title: 'Registros',
    templates: 'Plantillas de registro',
    recent: 'Registros recientes',
    noTemplates: 'Próximamente habrá plantillas disponibles',
  },
  skills: {
    title: 'Habilidades',
    subtitle: 'Recursos por emoción e intensidad',
    noSkills: 'Próximamente habrá habilidades disponibles',
    duration: 'Duración',
    steps: 'Pasos',
  },
  cycle: {
    menstruacion: 'Menstruación',
    folicular: 'Folicular',
    ovulacion: 'Ovulación',
    lutea: 'Lútea',
    no_aplica: 'No aplica',
  },
  intensity: {
    1: 'Muy baja',
    2: 'Baja',
    3: 'Media',
    4: 'Alta',
    5: 'Muy alta',
  },
  sleep: {
    1: 'Muy mal',
    2: 'Mal',
    3: 'Regular',
    4: 'Bien',
    5: 'Muy bien',
  },
  hunger: {
    1: 'Sin hambre',
    2: 'Poco',
    3: 'Normal',
    4: 'Hambriento',
    5: 'Mucho hambre',
  },
  emotionalRegister: {
    title: 'Registro emocional',
    subtitle: 'Observar y describir emociones',
    ctaTitle: 'Observar y describir',
    ctaSubtitle: 'Describe una emoción en detalle',
    emotion: 'Nombre de la emoción',
    emotionCustomPlaceholder: 'O escribe el nombre de la emoción...',
    intensity: 'Intensidad (1-10)',
    vulnerability: 'Vulnerabilidad',
    vulnerabilityPlaceholder: '¿Qué factores te hacían vulnerable?',
    trigger: 'Detonante',
    triggerPlaceholder: '¿Qué desencadenó la emoción?',
    interpretations: 'Interpretaciones',
    interpretationsPlaceholder: '¿Qué pensamientos o interpretaciones tuviste?',
    internalSensations: 'Sensaciones internas',
    internalSensationsPlaceholder: '¿Qué sentiste en tu cuerpo?',
    externalLanguage: 'Lenguaje externo',
    externalLanguagePlaceholder: '¿Qué expresaste con tu cara, postura o voz?',
    impulses: 'Impulsos',
    impulsesPlaceholder: '¿Qué tuviste ganas de hacer?',
    behavior: 'Conducta',
    behaviorPlaceholder: '¿Qué hiciste realmente?',
    consequences: 'Consecuencias',
    consequencesPlaceholder: '¿Qué consecuencias tuvo tu conducta?',
    emotionFunction: 'Función de la emoción',
    emotionFunctionPlaceholder: '¿Para qué sirvió esta emoción?',
    save: 'Guardar registro',
    saved: 'Registro guardado',
    detail: 'Detalle',
    intensityOf10: '/10',
    customEmotion: 'Emoción personalizada',
  },
  sharing: {
    title: 'Compartir',
    subtitle: 'Comparte tu jardín emocional',
    generateCode: 'Generar código',
    codeLabel: 'Tu código de invitación',
    codeExpiry: 'Expira en 24 horas',
    codeCopied: 'Código copiado al portapapeles',
    enterCode: 'Introducir código',
    enterCodePlaceholder: 'Ej: ABC123',
    enterCodeHint: 'Pide el código a la persona que quiere compartir contigo',
    link: 'Vincular',
    linking: 'Vinculando...',
    viewer: 'Quién ve mi jardín',
    noViewer: 'No has compartido con nadie',
    sharedWith: 'Jardín compartido conmigo',
    noShared: 'Nadie ha compartido contigo',
    revokeAccess: 'Revocar acceso',
    revokeConfirmTitle: 'Revocar acceso',
    revokeConfirmMessage: '¿Estás segura de que quieres quitar el acceso a esta persona?',
    tabTitle: 'Compartido',
    readOnly: 'Solo lectura',
    viewingGarden: 'Jardín de',
    todaySection: 'Hoy',
    calendarSection: 'Calendario',
    summarySection: 'Resumen',
    noLink: 'No tienes ningún jardín vinculado',
    noLinkHint: 'Ve a tu perfil para vincular un código de invitación',
    totalCheckins: 'Check-ins totales',
    uniqueDays: 'Días activos',
    topEmotion: 'Emoción principal',
    errorInvalidCode: 'El código no es válido',
    errorExpiredCode: 'El código ha expirado',
    errorSelfLink: 'No puedes vincularte a ti misma',
    errorAlreadyLinked: 'Ya estás vinculada con esta persona',
    errorLinkRevoked: 'El acceso fue revocado por el propietario',
    successLinked: 'Vinculación exitosa',
  },
  garden: {
    title: 'Tu jardín',
    flowersPlanted: 'flores plantadas',
    topEmotion: 'Más plantada',
    emptyTitle: 'Tu jardín está vacío',
    emptyMessage: 'Haz tu primer registro y planta tu primera flor',
    emptyButton: 'Plantar mi primera flor',
    viewGarden: 'Ver jardín →',
    todayEmpty: '🪴',
    rainbow: '🌈',
    modeView: 'Mirar',
    modeMove: 'Mover',
    modeDecorate: 'Decorar',
    modeWater: 'Regar',
    tapToPlace: 'Toca una celda para colocar',
    tapToMove: 'Mantén pulsada una planta para moverla',
    decorationPlaced: 'Decoración colocada',
    decorationRemoved: 'Decoración eliminada',
    photoMode: 'Foto',
    photoSaved: 'Foto guardada en tu galería',
    achievements: 'Logros',
    newAchievement: '¡Nuevo logro!',
  },
  shop: {
    title: 'Tienda',
    seedUnit: '🌰',
    tabDecorations: 'Decorar',
    tabPets: 'Mascotas',
    tabCosmetics: 'Temas',
    tabTerrain: 'Terreno',
    confirmTitle: 'Comprar',
    buyButton: 'Comprar',
    insufficientTitle: 'Semillas insuficientes',
    insufficientMessage: 'Necesitas más semillas. Haz check-ins y riega tus plantas para ganar más.',
    purchased: 'Comprado',
    earnedSeeds: 'semillas ganadas',
    dailyReward: 'Recompensa diaria',
    streakBonus: 'Bonus de racha',
    waterBonus: 'Bonus de riego',
  },
  common: {
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    edit: 'Editar',
    back: 'Volver',
    loading: 'Cargando...',
    error: 'Ha ocurrido un error',
    retry: 'Reintentar',
  },
  premium: {
    title: 'Premium',
    badge: 'Premium',
    activeTitle: 'Eres Premium',
    giftCodeLabel: 'Código de regalo',
    giftCodePlaceholder: 'Ej: ABC123',
    giftCodeHint: 'Introduce un código de regalo para desbloquear Premium',
    redeem: 'Canjear',
    redeeming: 'Canjeando...',
    successRedeemed: 'Premium activado',
    expiresOn: 'Activo hasta',
    errorInvalidCode: 'El código no es válido',
    errorExpiredCode: 'El código ha expirado',
    errorAlreadyRedeemed: 'Este código ya fue canjeado',
  },
  greeting: {
    morning: 'Buenos días',
    afternoon: 'Buenas tardes',
    evening: 'Buenas noches',
  },
};
