export const strings = {
  app: {
    name: 'Bloom',
  },
  tabs: {
    checkin: 'Registros',
    calendar: 'Calendario',
    registers: 'Registros',
    records: 'Buscar',
    skills: 'Habilidades',
    profile: 'Tu',
  },
  auth: {
    login: 'Iniciar sesión',
    register: 'Crear cuenta',
    forgotPassword: 'Recuperar contraseña',
    email: 'Correo electrónico',
    password: 'Contraseña',
    confirmPassword: 'Confirmar contraseña',
    displayName: 'Nombre',
    loginButton: 'Entrar',
    registerButton: 'Registrarse',
    forgotPasswordButton: 'Enviar enlace',
    noAccount: '¿No tienes cuenta?',
    hasAccount: '¿Ya tienes cuenta?',
    forgotPasswordLink: '¿Olvidaste tu contraseña?',
    backToLogin: 'Volver al inicio',
    logout: 'Cerrar sesión',
    genderLabel: 'Forma de tratamiento',
    genderFeminine: 'Femenino',
    genderMasculine: 'Masculino',
    genderNeutral: 'Neutro',
  },
  checkin: {
    title: '¿Cómo te has sentido hoy?',
    newCheckin: 'Registro diario',
    todayRecords: 'Registros de hoy',
    noRecordsToday: 'Aún no has registrado nada hoy',
    emotion: '¿Cuál es tu emoción predominante?',
    intensity: 'Intensidad',
    sleep: '¿Cómo has dormido?',
    hunger: 'Nivel de hambre',
    cycle: 'Fase del ciclo',
    events: 'Eventos importantes',
    eventTitle: 'Título del evento',
    eventDescription: 'Descripción',
    addEvent: 'Añadir otro evento',
    notes: 'Notas adicionales',
    notesPlaceholder: 'Escribe lo que quieras...',
    save: 'Guardar registro',
    saved: 'Registro guardado',
    sectionDaily: 'Registros diarios',
    sectionEmotional: 'Registros emocionales',
  },
  calendar: {
    title: 'Calendario',
    noRecords: 'No hay registros para este día',
    addRecord: 'Añadir registro',
  },
  tu: {
    insights: 'Insights',
    insightsDesc: 'Tu resumen emocional',
    compartido: 'Compartido',
    compartidoDesc: 'Jardín compartido contigo',
    habilidades: 'Habilidades',
    habilidadesDesc: 'Recursos y técnicas',
    compartirDatos: 'Compartir datos',
    compartirDatosDesc: 'Gestiona quién ve tu jardín',
    planSeguridad: 'Plan de seguridad',
    planSeguridadDesc: 'Tu red de apoyo personal',
    premium: 'Premium',
    premiumDesc: 'Desbloquea funciones avanzadas',
    settings: 'Ajustes',
    about: 'Acerca de',
    version: 'Versión',
  },
  search: {
    title: 'Buscar',
    subtitle: 'Busca en tus registros',
    segmentAll: 'Todos',
    segmentCheckin: 'Registro',
    segmentRegister: 'Observar y describir',
    placeholder: 'Buscar por texto...',
    emotionsLabel: 'Filtrar por emociones',
    dateFrom: 'Desde',
    dateTo: 'Hasta',
    searchButton: 'Buscar',
    clearFilters: 'Limpiar filtros',
    results: 'resultados',
    oneResult: 'resultado',
    noResults: 'No se encontraron registros',
    noResultsHint: 'Prueba con otros filtros o términos de búsqueda',
    noRecords: 'Aún no tienes registros',
  },
  registers: {
    title: 'Registros',
    templates: 'Plantillas de registro',
    recent: 'Registros recientes',
    noTemplates: 'Próximamente habrá plantillas disponibles',
  },
  skills: {
    title: 'Habilidades',
    subtitle: 'Técnicas y ejercicios basados en DBT',
    noSkills: 'Próximamente habrá habilidades disponibles',
    duration: 'Duración',
    steps: 'Pasos',
    exercise: 'Ejercicio',
    article: 'Artículo',
    allTypes: 'Todas',
    exercises: 'Ejercicios',
    articles: 'Artículos',
    startExercise: 'Comenzar ejercicio',
    practiceArticle: 'He practicado esto',
    stepOf: 'Paso {current} de {total}',
    nextStep: 'Siguiente',
    finish: 'Finalizar',
    pause: 'Pausar',
    resume: 'Reanudar',
    congratulations: '¡Bien hecho!',
    practiceRecorded: 'Práctica registrada',
    keepPracticing: 'Cada vez que practiques, será más fácil',
    backToSkills: 'Volver a habilidades',
    practiceAgain: 'Practicar de nuevo',
    practiceHistory: 'Historial',
    totalPractices: 'Prácticas totales',
    uniqueSkills: 'Habilidades diferentes',
    totalTime: 'Tiempo total',
    minutes: 'min',
    noPractices: 'Aún no has practicado ninguna habilidad',
    noPracticesHint: 'Explora las categorías y completa tu primer ejercicio',
    suggestedForYou: 'Sugerido para ti',
    filterByEmotion: 'Filtrar por emoción',
    skillCount: '{count} habilidades',
    tips: 'Consejos',
    practicesSummary: '{count} prácticas realizadas',
  },
  cycle: {
    menstruacion: 'Menstruación',
    folicular: 'Folicular',
    ovulacion: 'Ovulación',
    lutea: 'Lútea',
    no_aplica: 'No aplica',
  },
  intensity: {
    1: 'Muy baja',
    2: 'Baja',
    3: 'Media',
    4: 'Alta',
    5: 'Muy alta',
  },
  sleep: {
    1: 'Muy mal',
    2: 'Mal',
    3: 'Regular',
    4: 'Bien',
    5: 'Muy bien',
  },
  hunger: {
    1: 'Sin hambre',
    2: 'Poco',
    3: 'Normal',
    4: 'Hambriento',
    5: 'Mucho hambre',
  },
  emotionalRegister: {
    title: 'Registro emocional',
    subtitle: 'Observar y describir emociones',
    ctaTitle: 'Observar y describir',
    ctaSubtitle: 'Describe una emoción en detalle',
    emotion: 'Nombre de la emoción',
    emotionCustomPlaceholder: 'O escribe el nombre de la emoción...',
    intensity: 'Intensidad (1-10)',
    vulnerability: 'Vulnerabilidad',
    vulnerabilityPlaceholder: '¿Qué factores te hacían vulnerable?',
    trigger: 'Detonante',
    triggerPlaceholder: '¿Qué desencadenó la emoción?',
    interpretations: 'Interpretaciones',
    interpretationsPlaceholder: '¿Qué pensamientos o interpretaciones tuviste?',
    internalSensations: 'Sensaciones internas',
    internalSensationsPlaceholder: '¿Qué sentiste en tu cuerpo?',
    externalLanguage: 'Lenguaje externo',
    externalLanguagePlaceholder: '¿Qué expresaste con tu cara, postura o voz?',
    impulses: 'Impulsos',
    impulsesPlaceholder: '¿Qué tuviste ganas de hacer?',
    behavior: 'Conducta',
    behaviorPlaceholder: '¿Qué hiciste realmente?',
    consequences: 'Consecuencias',
    consequencesPlaceholder: '¿Qué consecuencias tuvo tu conducta?',
    emotionFunction: 'Función de la emoción',
    emotionFunctionPlaceholder: '¿Para qué sirvió esta emoción?',
    save: 'Guardar registro',
    saved: 'Registro guardado',
    detail: 'Detalle',
    intensityOf10: '/10',
    customEmotion: 'Emoción personalizada',
  },
  sharing: {
    title: 'Compartir',
    subtitle: 'Comparte tu jardín emocional',
    generateCode: 'Generar código',
    codeLabel: 'Tu código de invitación',
    codeExpiry: 'Expira en 24 horas',
    codeCopied: 'Código copiado al portapapeles',
    enterCode: 'Introducir código',
    enterCodePlaceholder: 'Ej: ABC123',
    enterCodeHint: 'Pide el código a la persona que quiere compartir contigo',
    link: 'Vincular',
    linking: 'Vinculando...',
    viewer: 'Quién ve mi jardín',
    noViewer: 'No has compartido con nadie',
    sharedWith: 'Jardín compartido conmigo',
    noShared: 'Nadie ha compartido contigo',
    revokeAccess: 'Revocar acceso',
    revokeConfirmTitle: 'Revocar acceso',
    revokeConfirmMessage: {
      f: '¿Estás segura de que quieres quitar el acceso a esta persona?',
      m: '¿Estás seguro de que quieres quitar el acceso a esta persona?',
      n: '¿Seguro/a de que quieres quitar el acceso a esta persona?',
    },
    tabTitle: 'Compartido',
    readOnly: 'Solo lectura',
    viewingGarden: 'Jardín de',
    todaySection: 'Hoy',
    calendarSection: 'Calendario',
    summarySection: 'Resumen',
    noLink: 'No tienes ningún jardín vinculado',
    noLinkHint: 'Ve a tu perfil para vincular un código de invitación',
    totalCheckins: 'Registros totales',
    uniqueDays: 'Días activos',
    topEmotion: 'Emoción principal',
    errorInvalidCode: 'El código no es válido',
    errorExpiredCode: 'El código ha expirado',
    errorSelfLink: 'No puedes vincularte a ti misma',
    errorAlreadyLinked: {
      f: 'Ya estás vinculada con esta persona',
      m: 'Ya estás vinculado con esta persona',
      n: 'Ya tienes un vínculo con esta persona',
    },
    errorLinkRevoked: 'El acceso fue revocado por el propietario',
    successLinked: 'Vinculación exitosa',
  },
  garden: {
    title: 'Tu jardín',
    flowersPlanted: 'flores plantadas',
    topEmotion: 'Más plantada',
    emptyTitle: 'Tu jardín está vacío',
    emptyMessage: 'Haz tu primer registro y planta tu primera flor',
    emptyButton: 'Plantar mi primera flor',
    viewGarden: 'Ver jardín →',
    todayEmpty: '🪴',
    rainbow: '🌈',
    modeView: 'Mirar',
    modeMove: 'Mover',
    modeDecorate: 'Decorar',
    modeWater: 'Regar',
    tapToPlace: 'Toca una celda para colocar',
    tapToMove: 'Mantén pulsada una planta para moverla',
    decorationPlaced: 'Decoración colocada',
    decorationRemoved: 'Decoración eliminada',
    photoMode: 'Foto',
    photoSaved: 'Foto guardada en tu galería',
    shareTitle: 'Compartir jardín',
    sharing: 'Compartiendo...',
    shareError: 'No se pudo compartir la imagen',
    achievements: 'Logros',
    newAchievement: '¡Nuevo logro!',
  },
  shop: {
    title: 'Tienda',
    seedUnit: '🌰',
    tabDecorations: 'Decorar',
    tabPets: 'Mascotas',
    tabCosmetics: 'Temas',
    tabTerrain: 'Terreno',
    confirmTitle: 'Comprar',
    buyButton: 'Comprar',
    insufficientTitle: 'Semillas insuficientes',
    insufficientMessage: 'Necesitas más semillas. Haz registros y riega tus plantas para ganar más.',
    purchased: 'Comprado',
    earnedSeeds: 'semillas ganadas',
    dailyReward: 'Recompensa diaria',
    streakBonus: 'Bonus de racha',
    waterBonus: 'Bonus de riego',
  },
  compostar: {
    button: 'Compostar',
    title: 'Reflexiona y transforma',
    prompt: '¿Qué aprendiste de esta experiencia?',
    placeholder: 'Escribe tu reflexión...',
    minChars: 'Escribe al menos 30 caracteres',
    submit: 'Compostar y ganar 8 🌰',
    success: '¡Reflexión guardada! +8 🌰',
    alreadyDone: 'Compostado',
    reflectionLabel: 'Tu reflexión',
  },
  common: {
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    edit: 'Editar',
    back: 'Volver',
    loading: 'Cargando...',
    error: 'Ha ocurrido un error',
    retry: 'Reintentar',
  },
  premium: {
    title: 'Premium',
    badge: 'Premium',
    activeTitle: 'Eres Premium',
    giftCodeLabel: 'Código de regalo',
    giftCodePlaceholder: 'Ej: ABC123',
    giftCodeHint: 'Introduce un código de regalo para desbloquear Premium',
    redeem: 'Canjear',
    redeeming: 'Canjeando...',
    successRedeemed: 'Premium activado',
    expiresOn: 'Activo hasta',
    errorInvalidCode: 'El código no es válido',
    errorExpiredCode: 'El código ha expirado',
    errorAlreadyRedeemed: 'Este código ya fue canjeado',
  },
  subscription: {
    monthlyLabel: 'Mensual',
    monthlyPrice: '2,99 €/mes',
    annualLabel: 'Anual',
    annualPrice: '19,99 €/año',
    annualSave: 'Ahorra 40%',
    popular: 'Más popular',
    freeTrial: '7 días gratis',
    subscribe: 'Comenzar prueba gratuita',
    subscribing: 'Procesando...',
    restore: 'Restaurar compras',
    restoring: 'Restaurando...',
    finePrint: 'Se renovará automáticamente. Cancela en cualquier momento desde Ajustes.',
    successTitle: 'Bienvenida a Premium',
    successMessage: 'Tu prueba gratuita de 7 días ha comenzado.',
    restoreSuccess: 'Compras restauradas',
    restoreEmpty: 'No se encontraron compras previas',
    errorTitle: 'Error',
    errorPurchase: 'No se pudo completar la compra.',
    errorRestore: 'No se pudieron restaurar las compras.',
    errorOfferings: 'No se pudieron cargar los planes.',
    managedByStore: 'Gestiona tu suscripción desde los ajustes de tu dispositivo.',
  },
  insights: {
    title: 'Insights',
    subtitle: 'Tu resumen emocional',
    weeklyActivity: 'Actividad semanal',
    topEmotions: 'Emociones más frecuentes',
    avgIntensity: 'Intensidad media',
    avgSleep: 'Calidad de sueño',
    correlations: 'Correlaciones',
    sleepCorrelation: 'Sueño y emociones',
    whenSleepBad: 'Cuando duermes mal',
    whenSleepGood: 'Cuando duermes bien',
    cyclePatterns: 'Ciclo y emociones',
    dayOfWeek: 'Patrones por día',
    bestDay: 'Mejor día',
    hardestDay: 'Día más difícil',
    weeklyTrend: 'Tendencia semanal',
    moreOf: 'Más',
    lessOf: 'Menos',
    vsLastWeek: 'vs semana anterior',
    noChange: 'Sin cambios significativos',
    needMoreData: 'Necesitas al menos 7 registros para ver correlaciones',
    hungerCorrelation: 'Hambre y emociones',
    whenHungry: 'Con hambre alta',
    whenFed: 'Sin hambre',
  },
  gratitude: {
    title: 'Diario de gratitud',
    subtitle: 'Tres cosas buenas de hoy',
    placeholder1: {
      f: '1. Estoy agradecida por...',
      m: '1. Estoy agradecido por...',
      n: '1. Agradezco...',
    },
    placeholder2: {
      f: '2. Estoy agradecida por...',
      m: '2. Estoy agradecido por...',
      n: '2. Agradezco...',
    },
    placeholder3: {
      f: '3. Estoy agradecida por...',
      m: '3. Estoy agradecido por...',
      n: '3. Agradezco...',
    },
    save: 'Guardar gratitud',
    saved: 'Gratitud guardada',
    edit: 'Editar gratitud',
    ctaTitle: 'Diario de gratitud',
    ctaSubtitle: 'Tres cosas buenas de hoy',
    ctaDone: 'Gratitud de hoy',
    sectionTitle: 'Gratitud del día',
    emptyDay: 'Sin gratitud registrada este día',
  },
  achievements: {
    title: 'Logros',
    subtitle: 'Tu progreso en Bloom',
    sectionApp: 'Logros de bienestar',
    sectionGarden: 'Logros del jardín',
    locked: 'Bloqueado',
    unlocked: 'Desbloqueado',
    newAchievement: '¡Nuevo logro!',
    progress: 'Progreso',
    // App achievements
    firstCheckin: 'Primer paso',
    firstCheckinDesc: 'Haz tu primer registro',
    fiveCheckins: 'Constancia',
    fiveCheckinsDesc: 'Completa 5 registros',
    twentyFiveCheckins: 'Hábito formado',
    twentyFiveCheckinsDesc: 'Completa 25 registros',
    fiftyCheckins: 'Medio centenar',
    fiftyCheckinsDesc: 'Completa 50 registros',
    hundredCheckins: { f: 'Centenaria', m: 'Centenario', n: 'Cien registros' },
    hundredCheckinsDesc: 'Completa 100 registros',
    streak3: 'Tres al hilo',
    streak3Desc: '3 días consecutivos',
    streak7: 'Una semana',
    streak7Desc: '7 días consecutivos',
    streak14: 'Dos semanas',
    streak14Desc: '14 días consecutivos',
    streak30: 'Un mes',
    streak30Desc: '30 días consecutivos',
    streak60: 'Dos meses',
    streak60Desc: '60 días consecutivos',
    firstGratitude: { f: 'Agradecida', m: 'Agradecido', n: 'Gratitud' },
    firstGratitudeDesc: 'Escribe tu primera gratitud',
    sevenGratitudes: 'Semana de gratitud',
    sevenGratitudesDesc: 'Escribe 7 entradas de gratitud',
    allEmotions: 'Arcoíris emocional',
    allEmotionsDesc: 'Usa las 12 emociones',
    firstCompost: 'Primera reflexión',
    firstCompostDesc: 'Composta tu primer registro',
    fiveComposts: { f: 'Transformadora', m: 'Transformador', n: 'Transformación' },
    fiveCompostsDesc: 'Composta 5 registros',
    // Skills achievements
    firstPractice: 'Primera práctica',
    firstPracticeDesc: 'Completa tu primer ejercicio',
    fivePractices: 'Practicante',
    fivePracticesDesc: 'Completa 5 ejercicios',
    fifteenPractices: { f: 'Habilidosa', m: 'Habilidoso', n: 'Gran habilidad' },
    fifteenPracticesDesc: 'Completa 15 ejercicios',
    allCategories: { f: 'Exploradora', m: 'Explorador', n: 'Exploración total' },
    allCategoriesDesc: 'Practica en las 5 categorías',
  },
  agenda: {
    title: 'Mi Diario',
    subtitle: 'Tu historia emocional',
    searchPlaceholder: 'Buscar en tu diario...',
    emptyState: 'Tu diario está vacío.\nComienza a registrar tu bienestar.',
    gratitudeLabel: 'Gratitud',
    totalEntries: 'entradas',
    oneEntry: 'entrada',
    segmentGratitude: 'Gratitud',
  },
  greeting: {
    morning: 'Buenos días',
    afternoon: 'Buenas tardes',
    evening: 'Buenas noches',
  },
  safetyPlan: {
    title: 'Plan de seguridad',
    subtitle: 'Tu red de apoyo personal',
    warningSigns: 'Señales de alerta',
    warningSignsDesc: 'Pensamientos, emociones o situaciones que indican que necesitas apoyo',
    warningSignPlaceholder: 'Ej: No puedo dejar de llorar...',
    copingStrategies: 'Estrategias de afrontamiento',
    copingStrategiesDesc: 'Cosas que puedes hacer por ti misma para sentirte mejor',
    copingStrategyPlaceholder: 'Ej: Salir a caminar...',
    trustedContacts: 'Contactos de confianza',
    trustedContactsDesc: 'Personas a las que puedes llamar cuando necesites apoyo',
    contactNamePlaceholder: 'Nombre',
    contactPhonePlaceholder: 'Teléfono',
    personalSteps: 'Mis pasos personales',
    personalStepsDesc: 'Acciones concretas que puedes seguir en un momento difícil',
    personalStepPlaceholder: 'Ej: Respirar 5 veces profundamente...',
    crisisHotlines: 'Líneas de crisis',
    crisisHotlinesDesc: 'Servicios profesionales disponibles 24/7',
    callConfirmTitle: 'Llamar',
    callConfirmMessage: '¿Quieres llamar a {name}?',
    callHotlineMessage: '¿Quieres llamar a {name}?',
    call: 'Llamar',
    saved: 'Plan guardado',
    disclaimer: 'Este plan es una herramienta personal de apoyo. En caso de emergencia, llama al servicio de emergencias de tu país o acude al centro de salud más cercano.',
  },
  breathing: {
    inhale: 'Inhala',
    hold: 'Retén',
    exhale: 'Exhala',
    breathe: 'Respira',
  },
  socialAuth: {
    divider: 'o continuar con',
    apple: 'Continuar con Apple',
    google: 'Continuar con Google',
  },
  deleteAccount: {
    title: 'Eliminar cuenta',
    warning: 'Esta acción es permanente e irreversible. Se eliminarán todos tus datos.',
    whatDeleted: 'Se eliminará:',
    itemCheckins: 'Todos tus check-ins y registros emocionales',
    itemGratitude: 'Tu diario de gratitud',
    itemGarden: 'Tu jardín y logros',
    itemSafetyPlan: 'Tu plan de seguridad',
    itemSharing: 'Vínculos de compartir',
    itemAccount: 'Tu cuenta y perfil',
    reAuthTitle: 'Verificar identidad',
    reAuthPassword: 'Introduce tu contraseña para continuar',
    reAuthApple: 'Verificar con Apple',
    reAuthGoogle: 'Verificar con Google',
    confirmButton: 'Eliminar cuenta permanentemente',
    deleting: 'Eliminando datos...',
    success: 'Cuenta eliminada correctamente',
    errorReAuth: 'No se pudo verificar tu identidad',
    errorDelete: 'Error al eliminar la cuenta. Inténtalo de nuevo.',
  },
  disclaimer: {
    text: 'Bloom es una herramienta de bienestar emocional y no pretende diagnosticar, tratar, curar ni prevenir ninguna enfermedad o trastorno mental. No sustituye el consejo, diagnóstico o tratamiento médico profesional. Si necesitas ayuda profesional, consulta a un especialista.',
  },
  privacyPolicy: {
    title: 'Política de privacidad',
    link: 'Política de privacidad',
  },
  walkthrough: {
    step1Title: 'Tu espacio de bienestar',
    step1Text: 'Aquí verás tu racha, registros del día y accesos directos.',
    step2Title: 'Registra cómo te sientes',
    step2Text: 'Haz un check-in diario o describe una emoción en detalle.',
    step3Title: 'Tu diario personal',
    step3Text: 'Accede a tu diario completo tocando el libro flotante.',
    step4Title: 'Habilidades',
    step4Text: 'Ejercicios y técnicas basados en terapia dialéctica conductual.',
    step5Title: 'Tu perfil',
    step5Text: 'Insights, logros, ajustes y tu plan de seguridad.',
    next: 'Siguiente',
    skip: 'Omitir',
    done: 'Entendido',
  },
};
